# Generated by Django 4.0.5 on 2022-06-27 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/user_uploaded_images', verbose_name='image')),
                ('image_name', models.CharField(max_length=250, verbose_name='image name')),
                ('is_image_grouped', models.BooleanField(blank=True, null=True, verbose_name='is image grouped')),
                ('image_group', models.CharField(max_length=5, null=True, verbose_name='image group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
    ]
