# Generated by Django 4.0.5 on 2022-06-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='is_image_grouped',
        ),
        migrations.AddField(
            model_name='image',
            name='image_features',
            field=models.TextField(blank=True, null=True, verbose_name='image_features'),
        ),
    ]
