# Generated by Django 4.0.5 on 2022-06-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_image_is_image_grouped_image_image_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_features',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_group',
            field=models.IntegerField(max_length=5, null=True, verbose_name='image group'),
        ),
    ]
